---
- name: Adicionar a chave GPG do Fluent Bit
  ansible.builtin.apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Adicionar o repositório do Fluent Bit
  ansible.builtin.apt_repository:
    repo: "deb https://packages.fluentbit.io/ubuntu/focal focal main"
    state: present

- name: Instalar o Fluent Bit
  ansible.builtin.apt:
    name: fluent-bit
    state: present
    update_cache: yes

- name: Criar diretorios de buffer para o Fluent Bit (SO)
  ansible.builtin.file:
    path: /var/log/fluentbit-buffer/so
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Criar diretorio de buffer para as Aplicacoes
  ansible.builtin.file:
    path: "/var/log/fluentbit-buffer/apps/{{ item.id_bucket }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ aplicacoes | default([]) }}"
  when: aplicacoes is defined

- name: Criar diretorio de buffer para Apache
  ansible.builtin.file:
    path: /var/log/fluentbit-buffer/apache
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: perfil_apache | default(false) | bool

- name: Implantar configuracao do Fluent Bit (Template)
  ansible.builtin.template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart fluent-bit

- name: Configurar credenciais OCI S3 como variaveis de ambiente
  ansible.builtin.copy:
    content: |
      AWS_ACCESS_KEY_ID={{ s3_access_key }}
      AWS_SECRET_ACCESS_KEY={{ s3_secret_key }}
    dest: /etc/default/fluent-bit
    owner: root
    group: root
    mode: '0600' # Protege o arquivo para que apenas o root consiga ver as chaves
  notify: Restart fluent-bit

- name: Garantir que o servico do Fluent Bit esta rodando e habilitado
  ansible.builtin.systemd:
    name: fluent-bit
    state: started
    enabled: yes

- name: Configurar logrotate para as aplicacoes
  ansible.builtin.copy:
    dest: /etc/logrotate.d/aplicacoes
    owner: root
    group: root
    mode: '0644'
    content: |
      {% for app in aplicacoes %}
      {% if app.tipo_app == 'rails' %}
      /home/ubuntu/AdAlive-Apps/{{ app.nome_pasta }}/AdAliveServer/*.log {
          su ubuntu ubuntu
          daily
          missingok
          rotate 7
          compress
          notifempty
          copytruncate
          dateext
          dateformat .%Y-%m-%d
      }
      {% elif app.tipo_app == 'tomcat' %}
      /home/ubuntu/AdAlive-Apps/{{ app.nome_pasta }}/logs/*.log
      /home/ubuntu/AdAlive-Apps/{{ app.nome_pasta }}/logs/*.txt {
          su ubuntu ubuntu
          daily
          missingok
          rotate 7
          compress
          notifempty
          copytruncate
          dateext
          dateformat .%Y-%m-%d
      }
      {% endif %}
      {% endfor %}
  when: aplicacoes is defined