---
- name: Adicionar a chave GPG do Fluent Bit
  ansible.builtin.apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Adicionar o repositório do Fluent Bit
  ansible.builtin.apt_repository:
    repo: "deb https://packages.fluentbit.io/ubuntu/focal focal main" # Ajuste a versão do SO se necessário (focal, jammy, etc.)
    state: present

- name: Instalar o Fluent Bit
  ansible.builtin.apt:
    name: fluent-bit
    state: present
    update_cache: yes

- name: Criar diretorios de buffer para o Fluent Bit
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /var/log/fluentbit-buffer/app
    - /var/log/fluentbit-buffer/so

- name: Implantar configuracao do Fluent Bit (Template)
  ansible.builtin.template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart fluent-bit

- name: Configurar credenciais OCI S3 como variaveis de ambiente
  ansible.builtin.copy:
    content: |
      AWS_ACCESS_KEY_ID={{ s3_access_key }}
      AWS_SECRET_ACCESS_KEY={{ s3_secret_key }}
    dest: /etc/default/fluent-bit
    owner: root
    group: root
    mode: '0600' # Protege o arquivo para que apenas o root consiga ver as chaves
  notify: Restart fluent-bit

- name: Garantir que o servico do Fluent Bit esta rodando e habilitado
  ansible.builtin.systemd:
    name: fluent-bit
    state: started
    enabled: yes