[homologacao]
hmg-col-102 ansible_host=172.33.18.109 ansible_user=ubuntu nome_servidor=hmg-col-102

[producao]
prd-nov-101 ansible_host=172.33.28.150 ansible_user=ubuntu nome_servidor=prd-nov-101

prd-nov-102 ansible_host=172.33.24.163 ansible_user=ubuntu nome_servidor=prd-nov-102