[homologacao]
hmg-col-102 ansible_host=172.33.18.109 ansible_user=ubuntu nome_servidor=hmg-col-102 perfil_rails=true perfil_apache=true nome_app="AdAlive-doTerrahmlg" arquivo_log="rails_server_doterrahmlg.log"

[producao]
prd-nov-102 ansible_host=172.33.24.163 ansible_user=ubuntu nome_servidor=prd-nov-102 perfil_rails=true perfil_apache=true nome_app="AdAlive-Camprevrh" arquivo_log="rails_server_camprevrh.log"