[homologacao]
hmg-col-102 ansible_host=172.33.18.109 ansible_user=ubuntu nome_servidor=hmg-col-102 perfil_rails=true perfil_apache=true

[producao]
#prd-pet-101 ansible_host=10.0.0.5 ansible_user=ubuntu nome_servidor=prd-pet-101 perfil_rails=false perfil_apache=true