---
perfil_apache: true

# Aplicações AdAlive Ruby on Rails

aplicacoes:
  - id_bucket: "adalive-camprevrh"
    nome_pasta: "AdAlive-Camprevrh"
    tipo_app: "rails"
    tipo_backup: "fonte"
    log_principal: "rails_server_camprevrh.log"

  - id_bucket: "adalive-camprev2"
    nome_pasta: "AdAlive-Camprev2"
    tipo_app: "rails"
    tipo_backup: "fonte"
    log_principal: "rails_server_camprev2.log"

  # Aplicações Java Tomcat

  - id_bucket: "camprev-novaprev"
    caminho_base: "/home/ubuntu"                                      # <--- Caminho base real
    nome_pasta: "apache-tomcat-9.0.21-prd-novaprev"                   # Ajuste para a pasta real do servidor, se necessário
    tipo_app: "tomcat"

  - id_bucket: "camprev-novaprev-debug"
    caminho_base: "/home/ubuntu"
    nome_pasta: "apache-tomcat-9.0.21-prd-novaprev-debug"
    tipo_app: "tomcat"
    
  - id_bucket: "camprev-folha"
    caminho_base: "/home/ubuntu"
    nome_pasta: "apache-tomcat-9.0.21-prd-folha"
    tipo_app: "tomcat"
    

  # Micros serviços Java Quarkus para logs

  - id_bucket: "ms-camprev-novaprev-notificacoes"
    caminho_base: "/u01/microservices"
    nome_pasta: "" # Deixe vazio pois o caminho_base já aponta direto
    tipo_app: "quarkus"
    log_principal: "camprev-novaprev-ms-notificacoes-service.log" 

  - id_bucket: "ms-folha-notificacoes"
    caminho_base: "/u01/microservices"
    nome_pasta: "" 
    tipo_app: "quarkus"
    log_principal: "folha-notificacoes-service.log"

  - id_bucket: "ms-busca-cep"
    caminho_base: "/u01/microservices"
    nome_pasta: "" 
    tipo_app: "quarkus"
    log_principal: "ms-busca-cep-service.log"

  - id_bucket: "ms-convenio-medico"
    caminho_base: "/u01/microservices"
    nome_pasta: "" 
    tipo_app: "quarkus"
    log_principal: "ms-convenio-medico-service.log"

  - id_bucket: "ms-folhapar-ged"
    caminho_base: "/u01/microservices"
    nome_pasta: "" 
    tipo_app: "quarkus"
    log_principal: "ms-folhapar-ged-service.log"
  
  - id_bucket: "ms-motor-prova-vida"
    caminho_base: "/u01/microservices"
    nome_pasta: "" 
    tipo_app: "quarkus"
    log_principal: "ms-motor-prova-vida-service.log"

  - id_bucket: "ms-novaprev-ged"
    caminho_base: "/u01/microservices"
    nome_pasta: "" 
    tipo_app: "quarkus"
    log_principal: "ms-novaprev-ged-service.log"

  - id_bucket: "atlhub"
    caminho_base: "/u01/microservices"
    nome_pasta: "" 
    tipo_app: "quarkus"
    log_principal: "nohup-atlhub.log"